name: AssetRelativePath
id  : AssetRelativePath
key:  assetrelativepath
version: 1.1
author_link: http://www.skyarc.co.jp
author_name: SKYARC System Co., Ltd,
config_uri: https://raw.github.com/...
archive_uri: https://github.com/...http://www.skyarc.co.jp/engineerblog/entry/assetrelativepath.html
l10n_class: AssetRelativePath::L10N
description: <__trans phrase="Insert an item with a relative path">
config_template: config.tmpl
blog_config_template: config.tmpl
callbacks:
    MT::App::CMS::template_param.asset_insert: $assetrelativepath::AssetRelativePath::Plugin::hdlr_asset_relative_url
settings:
    assetrelativepath_search:
    assetrelativepath_replace: